LOAD DATA
TRUNCATE
INTO TABLE ERP_LOTE_ANULADO_TMP
FIELDS TERMINATED BY "|"
TRAILING NULLCOLS
(
LOTE_ID          INTEGER EXTERNAL,	      
FECHA		      DATE "YYYYMMDD",
MOTIVO		    CHAR,
FECHA_RECEPCION	  SYSDATE
)
